# ブロードキャスト

In [1]:
import numpy as np

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

# 要素へのアクセス

In [8]:
X = np.array([[51, 55], [14, 19], [0, 4]])
X

array([[51, 55],
       [14, 19],
       [ 0,  4]])

In [11]:
# 0行目
X[0]

array([51, 55])

In [12]:
#(0,1)の要素
X[0][1]

55

In [13]:
# Xを1次元の配列へ変換
X = X.flatten()
X

array([51, 55, 14, 19,  0,  4])

In [15]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [16]:
X > 15

array([ True,  True, False,  True, False, False])

In [17]:
X[X>15]

array([51, 55, 19])