# 多次元配列

In [1]:
import numpy as np

In [34]:
A = np.array([1, 2, 3, 4])

In [35]:
A

array([1, 2, 3, 4])

In [36]:
#次元数の取得
np.ndim(A)

1

In [37]:
#配列の形状
A.shape

(4,)

In [39]:
len(A)

4

In [40]:
A.shape[0]

4

In [41]:
B =np.array([[1,2], [3,4],[5,6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
len(B)

3

In [8]:
np.ndim(B)

2

In [9]:
B.shape

(3, 2)

# 行列の積

In [10]:
A = np.array([[1, 2], [3,4]])

In [11]:
A.shape

(2, 2)

In [12]:
B = np.array([[5, 6], [7,8]])
B.shape

(2, 2)

In [13]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [14]:
np.dot(B, A)

array([[23, 34],
       [31, 46]])

演算子の順番が異なると、結果も異なる。

## 2✖️3 と3✖️2の行列もできる

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [16]:
B = np.array([[1,2], [3, 4], [5, 6]])
B.shape

(3, 2)

In [17]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

## 2✖️3 と2✖️2の行列の積を行うとするとエラーが出力される。

In [18]:
C = np.array([[1,2], [3,4]])
C.shape

(2, 2)

In [19]:
A.shape

(2, 3)

In [20]:
np.dot(A, C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

## 対応する次元の要素は、 一致させる必要がある。

In [21]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A.shape

(3, 2)

In [22]:
B = np.array([7, 8])
B.shape

(2,)

In [23]:
np.dot(A, B)

array([23, 53, 83])

In [26]:
D = np.array([[[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]], 
       [[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]]])
D.shape

(2, 3, 4)

In [30]:
E = np.array([[[[1, ]]]])

<ipython-input-30-b3dc688d564b>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  E = np.array([[[[1., 1.], [1., 1.], [1., 1.], [1., 1.], ], [1., 1.], [1., 1.], [1., 1.], [1., 1.]]])


(1, 5)