# ニューラルネットワークの行列積

In [1]:
import numpy as np

In [2]:
X = np.array([1, 2])
X.shape

(2,)

In [3]:
W = np.array([[1, 3, 5], [2, 4, 6]])
W

array([[1, 3, 5],
       [2, 4, 6]])

In [4]:
W.shape

(2, 3)

In [5]:
Y = np.dot(X, W)
Y

array([ 5, 11, 17])

# 3層ニューラルネットワークの実装

In [9]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print("W1のshape")
print(W1.shape)
print("Xのshape")
print(X.shape)
print("B1のshape")
print(B1.shape)


A1=np.dot(X, W1) + B1
A1

W1のshape
(2, 3)
Xのshape
(2,)
B1のshape
(3,)


array([0.3, 0.7, 1.1])

In [14]:
# 活性化関数をシグモイド関数にしてみる。

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [16]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
Z2

array([0.62624937, 0.7710107 ])

In [17]:
# そのまま出力する関数「恒等関数」を定義
def identity_function(x):
    return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)
Y

array([0.31682708, 0.69627909])

# 実装のまとめ

In [18]:
# 活性化関数を用意

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

#  出力層の活性化関数を用意

def identity_function(x):
    return x

# 重みとバイアスの初期化を行い、ディクショナリ型の変数にいれるnetworkを用意

def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['B1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['B2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['B3'] = np.array([0.1, 0.2])
    
    return network

# 入力信号が出力へと変換するプロセスを実装

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    B1, B2, B3 =  network['B1'], network['B2'], network['B3']

    A1=np.dot(X, W1) + B1
    Z1 = sigmoid(A1)
    A2 = np.dot(Z1, W2) + B2
    Z2 = sigmoid(A2)
    A3 = np.dot(Z2, W3) + B3
    Y = identity_function(A3)
    
    return Y    

In [20]:
# 1個１個実装した時と同じ値を示すかを確かめる。
# array([0.31682708, 0.69627909])

In [21]:
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]
