# ソフトマックス関数

In [1]:
import numpy as np

In [2]:
a = np.array([0.3, 2.9, 4.0])

In [3]:
exp_a = np.exp(a)
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [4]:
sum_exp_a = np.sum(exp_a)
sum_exp_a

74.1221542101633

In [5]:
y = exp_a / sum_exp_a
y

array([0.01821127, 0.24519181, 0.73659691])

    まとめ

In [6]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y  =  exp_a / sum_exp_a
    
    return y

In [7]:
# 同じものができているかを確認。
softmax([0.3, 2.9, 4.0])

array([0.01821127, 0.24519181, 0.73659691])

# ソフトマックス関数の実装上の注意

In [8]:
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))

<ipython-input-8-23103c906500>:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
<ipython-input-8-23103c906500>:2: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [9]:
c = np.max(a)
a - c

array([  0, -10, -20])

In [10]:
np.exp(a - c ) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [11]:
# オーバーフロー対策

In [12]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y  =  exp_a / sum_exp_a
    
    return y

In [13]:
# 結果が変わらないことを確認。
softmax([0.3, 2.9, 4.0])

array([0.01821127, 0.24519181, 0.73659691])

# ソフトマックス関数の特徴

In [14]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)
np.sum(y)

[0.01821127 0.24519181 0.73659691]


1.0