# 多次元配列

In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3, 4])

In [3]:
A

array([1, 2, 3, 4])

In [4]:
#次元数の取得
np.ndim(A)

1

In [5]:
#配列の形状
A.shape

(4,)

In [6]:
A.shape[0]

4

In [7]:
B =np.array([[1,2], [3,4],[5,6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
np.ndim(B)

2

In [9]:
B.shape

(3, 2)

# 行列の積

In [10]:
A = np.array([[1, 2], [3,4]])

In [11]:
A.shape

(2, 2)

In [12]:
B = np.array([[5, 6], [7,8]])
B.shape

(2, 2)

In [13]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [14]:
np.dot(B, A)

array([[23, 34],
       [31, 46]])

演算子の順番が異なると、結果も異なる。